#ifndef __METALLICA_MIS_INIT_FLASH_H
#define __METALLICA_MIS_INIT_FLASH_H

/*
 * metallica_mis_init_flash.h
 *
 * C port of python-validity's validitysensor/init_flash.py -- the
 * pairing flow that runs once, the first time this daemon ever talks
 * to a fresh 06cb:009a sensor, to generate a client EC keypair,
 * partition the sensor's flash, and hand the sensor our key material
 * wrapped in a pre-shared-key envelope it can decrypt.
 *
 * SCOPE OF THIS FILE (read before adding to it):
 *
 * init_flash() in python-validity is NOT one self-contained function
 * -- most of it calls tls.cmd()/tls.handle_ecdh()/tls.handle_priv()/
 * tls.open(), all of which require the ECDH session object that only
 * metallica_mis_tls.c will provide (not written yet). Faking that
 * session here would violate the project's own rule (see
 * metallica_mis_daemon.c's header): don't stub fake crypto ahead of
 * the real handshake.
 *
 * What IS self-contained and safe to build now -- confirmed by
 * reading tls.py's Tls.set_hwkey(): the pre-shared "GWK" key pair
 * (psk_encryption_key / psk_validation_key) is derived purely from
 * password_hardcoded + gwk_sign_hardcoded + this host's product
 * name/serial, via the same PRF as everything else here. It does NOT
 * depend on ECDH or an open session. That means encrypt_key() (which
 * only needs those two PSK keys) is ALSO buildable now, even though
 * it isn't callable yet from a real init_flash() until partition_flash()
 * and the TLS session exist.
 *
 * Built here:
 *   - metallica_mis_prf()          -- TLS 1.2-style HMAC-SHA256 PRF,
 *                                      shared primitive python-validity
 *                                      uses for hs_key(), set_hwkey(),
 *                                      and (later) tls.c's make_keys()
 *   - metallica_mis_hs_key()       -- deterministic EC private scalar
 *                                      derived from password_hardcoded,
 *                                      used to sign make_cert()'s blob
 *   - metallica_mis_set_hwkey()    -- derives psk_encryption_key /
 *                                      psk_validation_key from host
 *                                      product name + serial
 *   - metallica_mis_encrypt_key()  -- AES-256-CBC + HMAC-SHA256 wrap
 *                                      of the client's EC keypair,
 *                                      ported from init_flash.py's
 *                                      encrypt_key()
 *   - metallica_mis_make_cert()    -- self-signed-by-hardcoded-key
 *                                      cert blob for the client's
 *                                      public key, ported from
 *                                      init_flash.py's make_cert()
 *   - metallica_mis_serialize_partition() / _flash_params() -- pure
 *                                      struct packing, no crypto
 *
 * NOT built here (needs metallica_mis_tls.c first):
 *   - partition_flash()  -- calls tls.cmd(), tls.handle_cert()
 *   - init_flash() itself -- calls get_flash_info()/erase_flash()/
 *     write_flash(), all of which route through tls.cmd(); also
 *     calls tls.handle_ecdh()/handle_priv()/open()
 *
 * TODO(metallica-mis): metallica_mis_set_hwkey() currently uses the
 * same 'VirtualBox'/'0' fallback python-validity uses when it can't
 * read /sys/class/dmi -- on macOS the equivalent would be reading
 * IOPlatformExpertDevice's model + IOPlatformSerialNumber via IOKit.
 * NOT wired up yet since it wasn't clear whether a Hackintosh's
 * OpenCore-spoofed SMBIOS strings even need to match anything the
 * real sensor pairing cares about -- flag this as an open question
 * before wiring the real IOKit call in.
 *
 * Depends on OpenSSL (or LibreSSL) for EC keygen, AES-CBC, HMAC-SHA256
 * -- same as noted as TBD in metallica_mis_daemon.c's build comment.
 */

#include <stddef.h>
#include <stdint.h>
#include <openssl/ec.h>

#define METALLICA_MIS_PRF_KEYLEN 0x20  /* 32 bytes, matches python-validity's key sizes */

/* metallica_mis_prf() -- TLS-1.2-style PRF: HMAC-SHA256 in the
 * P_hash() construction from RFC 5246 section 5. Writes exactly
 * `out_len` bytes to `out`. Direct port of tls.py's prf(). */
void metallica_mis_prf(const unsigned char *secret, size_t secret_len,
                        const unsigned char *seed, size_t seed_len,
                        unsigned char *out, size_t out_len);

/* metallica_mis_hs_key() -- deterministic EC private scalar derived
 * from password_hardcoded via the PRF, used only to sign make_cert()'s
 * blob (NOT the client's own per-device keypair -- that's freshly
 * generated by init_flash() itself, see metallica_mis_generate_client_keypair()
 * below). Writes 32 raw big-endian bytes to out[32]. Port of tls.py's
 * hs_key(), MINUS the final int() conversion -- python treats the PRF
 * output as a little-endian integer via [::-1].hex(); this returns
 * the reversed (big-endian) bytes directly so they can be fed to
 * EC_KEY_set_private_key() via BN_bin2bn(). */
void metallica_mis_hs_key(unsigned char out[32]);

/* metallica_mis_set_hwkey() -- derives the pre-shared "GWK" keys from
 * this host's product name + serial number. Port of tls.py's
 * Tls.set_hwkey(). Both out buffers must be METALLICA_MIS_PRF_KEYLEN
 * (32) bytes. See TODO above re: macOS IOKit product name/serial. */
void metallica_mis_set_hwkey(const char *product_name, const char *serial_number,
                              unsigned char psk_encryption_key[METALLICA_MIS_PRF_KEYLEN],
                              unsigned char psk_validation_key[METALLICA_MIS_PRF_KEYLEN]);

/* metallica_mis_generate_client_keypair() -- generates a fresh
 * SECP256R1 keypair for this session. This IS the "we generate a
 * fresh keypair locally" step Mohammad confirmed from python-validity
 * -- NOT reading any pre-existing device secret. Caller owns the
 * returned EC_KEY* and must EC_KEY_free() it. Returns NULL on
 * OpenSSL failure. */
EC_KEY *metallica_mis_generate_client_keypair(void);

/* metallica_mis_encrypt_key() -- AES-256-CBC (random IV) + HMAC-SHA256
 * wrap of the client's private scalar + public point (x||y||d, PKCS7
 * padded), keyed by the PSK pair from metallica_mis_set_hwkey().
 * Matches init_flash.py's encrypt_key() output layout exactly:
 *   [1 byte: 0x02] [16-byte IV] [ciphertext] [32-byte HMAC-SHA256 sig]
 * Returns malloc'd buffer via *out (caller frees), length via
 * *out_len. Returns 0 on success, -1 on failure. */
int metallica_mis_encrypt_key(const EC_KEY *client_keypair,
                               const unsigned char psk_encryption_key[METALLICA_MIS_PRF_KEYLEN],
                               const unsigned char psk_validation_key[METALLICA_MIS_PRF_KEYLEN],
                               unsigned char **out, size_t *out_len);

/* metallica_mis_make_cert() -- builds and signs (with hs_key(), NOT
 * the client's own key) the 444-byte cert blob embedding the client's
 * public point, per init_flash.py's make_cert(). Writes exactly 444
 * bytes to out[444]. Returns 0 on success, -1 on OpenSSL failure. */
int metallica_mis_make_cert(const EC_KEY *client_keypair, unsigned char out[444]);

/* metallica_mis_serialize_flash_params() / _serialize_partition() --
 * pure struct packing, no crypto, safe/simple to use whenever
 * partition_flash() eventually gets built against metallica_mis_tls.c.
 * Matches init_flash.py's serialize_flash_params()/serialize_partition()
 * byte layouts exactly. Both write to caller-provided buffers and
 * return the number of bytes written. */
size_t metallica_mis_serialize_flash_params(uint32_t ic_size, uint32_t sector_size,
                                             uint8_t sector_erase_cmd,
                                             unsigned char out[12]);

typedef struct {
    uint8_t  id;
    uint8_t  type;
    uint16_t access_lvl;
    uint32_t offset;
    uint32_t size;
} metallica_mis_partition_info_t;

/* Writes 12-byte packed header + 4 zero bytes + 32-byte SHA-256
 * digest of the 12-byte header = 48 bytes total, matching
 * init_flash.py's serialize_partition(). out must be >= 48 bytes. */
size_t metallica_mis_serialize_partition(const metallica_mis_partition_info_t *p,
                                          unsigned char out[48]);

#endif /* __METALLICA_MIS_INIT_FLASH_H */
